Miscellaneous cleanup (#1019)
* Add ortho imaged distance test where image correction has to work

* Distance test that actually needs to correct non-orthorhombic imaging

* Add minimum imaged vector output with magnitude test

* 6.18.1. Revision bump for temporarily disabling nxyz vector output from nastruct

* Remove nastruct nxyz set description from manual for now.

* pacman on appveyor seems broken for the VS 2015 image; lots of errors
like:
```
:: Retrieving packages...
error: failed retrieving file 'mingw-w64-x86_64-c-ares-1.15.0-1-any.pkg.tar.xz' from repo.msys2.org : The requested URL returned error: 404
```
This means that its not possible to pull in netcdf and the math
libraries. Disable the mingw cmake build since that requires netcdf. Try
to have the configure mingw build create its own libraries.

* Try to set the PATH so binaries can be properly found.

* Fix compile when netcdf not present

* Add -L to curl command to ensure redirects are followed

* Protect test when no netcdf

* Try a more sustainable way to set PATH

* Allocate data sets to store timecorr dplr data

* Add test save

* Remove references to _TC_DIPOLAR

* When get_library.sh fails, provide user more info on how to configure
without support of failed component.