Fix cpptraj build with Mac OS X (clang).  This was the build error:
PubFFT.cpp:52:8: error: no member named 'fill' in namespace 'std'
  std::fill(saved_work_, saved_work_+saved_work_size_, 0.0);
  ~~~~~^
PubFFT.cpp:160:8: error: no member named 'fill' in namespace 'std'
  std::fill(saved_factors_, saved_factors_+saved_factors_size_, 0);
  ~~~~~^

Needed to include <algorithm> to resolve the symbol.